= Quarkus - Ngrok
:extension-status: preview

This Quarkus extension integrates [ngrok](https://ngrok.com/) into Quarkus Dev Mode thus allowing users to expose their application to the public internet while they are still developing it.

NOTE: The extension has absolutely no impact on the production Quarkus application

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.ngrok:quarkus-ngrok` extension first.
In your `pom.xml` file, add:

[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.ngrok</groupId>
    <artifactId>quarkus-ngrok</artifactId>
</dependency>
----

== Usage

1. Add the extension to the application's dependencies `./mvnw quarkus:add-extension -Dextensions="io.quarkiverse.ngrok:quarkus-ngrok"`

2. Start Quarkus in Dev Mode with the following configuration property `quarkus.ngrok.enabled=true`. It is also advised for users to sign up for a free ngrok account and use the obtained token using `quarkus.ngrok.auth-token=sometoken` 

3. A short while after the application has started, you should see something in the application logs like:
+
[source,bash]
----
ngrok is running and its web interface can be accessed at: 'http://localhost:4040'
The application can be accessed publicly over the internet using: 'http://4f59-68-81-186-238.ngrok-free.app'
----
+
4. Use the `.ngrok-free.app` URL to access the running application from the public internet

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-ngrok.adoc[leveloffset=+1,opts=optional]
